"""

Constants for websockets

"""

PLAYER_POSITION = "PLAYER_POSITION"
PLAYER_KEY = "PLAYER_KEY"
PLAYER_JOINED = "PLAYER_JOINED"
PLAYER_LEFT = "PLAYER_LEFT"

PLAYER_SHOOT = "SHOOT"

MESSAGE_TYPES = {
    PLAYER_POSITION: 1,
    PLAYER_SHOOT: 2
}


# Game mechanics
ROOM_FRICTION = 1

PLAYER_MAX_SPEED = 5
PLAYER_ACCELERATION = .5
PLAYER_ROTATION_SPEED = 25

BULLET_SPEED = 20
MAX_BULLETS_PER_PLAYER = 1
BULLET_LIFESPAN = 3  # In seconds
